name: myntra_clone
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.0.0
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/ads/
    - assets/topnavigationBarIcons/
    - assets/bottomNavigationBarIcons/
